import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import type { Metadata } from "next";
import { Teko, Poppins } from "next/font/google";
import "./globals.css";
import Providers from "@/utils/Providers";
import { Toaster } from "react-hot-toast";

const teko = Teko({
  variable: "--font-teko",
  subsets: ["latin"],
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"], // optional, choose needed weights
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <ConfigProvider
          theme={{
            token: { colorPrimary: "#808080" },
            components: {
              Input: { borderRadius: 12, colorBorder: "#989898" },
              Select: { colorBgContainer: "#FFFFFF" },
              Collapse: { headerBg: "#404040" },
              Pagination: { itemActiveBg: "#808080" },
            },
          }}
        >
          <Providers>
            <AntdRegistry>
              {children}
              <Toaster />
            </AntdRegistry>
          </Providers>
        </ConfigProvider>
      </body>
    </html>
  );
}
